mysite/accounts/urls.py
from django.conf.urls import patterns, url

from accounts.forms import AuthenticationForm
from accounts.views import RegisterView


# Override some default keyword arguments for the default login and logout views
# If a view accepts keyword arguments, you can pass them in as the third argument when constructing
# a url.
# See: django/contrib/auth/views.py
login_overrides = {
    'authentication_form': AuthenticationForm,
    'template_name': 'accounts/login.html',
}

logout_overrides = {
    'template_name': 'accounts/logged_out.html',
}


urlpatterns = patterns(
    '',
    url(r'^login/$', 'django.contrib.auth.views.login', login_overrides, name='login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout', logout_overrides, name='logout'),
    url(r'^register/$', RegisterView.as_view(), name='register'),
)

mysite/api/urls.py
from django.conf.urls import patterns, url, include


urlpatterns = patterns(
    '',
    url(r'^v1/', include('api.v1.urls', namespace='v1')),
)

mysite/mysite/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.views.generic import TemplateView

from accounts.forms import AuthenticationForm


# Override a few default strings in the admin site
# See: https://docs.djangoproject.com/en/1.8/ref/contrib/admin/#adminsite-attributes
admin.site.site_header = "The Cisco Poller"
admin.site.site_title = "The Cisco Poller Admin"
admin.site.index_title = "Administration"

# Let's make the admin login page use our pretty login/logout pages
admin.site.login_form = AuthenticationForm
admin.site.login_template = 'accounts/login.html'
admin.site.logout_template = 'accounts/logged_out.html'


urlpatterns = patterns(
    '',
    url(r'^$', TemplateView.as_view(template_name='index.html'), name='index'),

    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^polls/', include('polls.urls', namespace='polls')),

    url(r'^api/', include('api.urls', namespace='api')),

    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

mysite/templates/base.html
<!DOCTYPE html>
{% load staticfiles common_tags %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>The Cisco Poller</title>

    <link href="{% static 'bootstrap/css/bootstrap.css' %}" rel="stylesheet">
    <link href="{% static 'bootstrap/css/bootstrap-theme.css' %}" rel="stylesheet">

    <link href="{% static 'css/style.css' %}" rel="stylesheet">

  </head>

  <body>

    {% block navbar %}
      <div class="navbar navbar-apple navbar-fixed-top" role="navigation">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'index' %}">
              The Cisco Poller
            </a>
          </div>
          <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <li><a href="{% url 'polls:index' %}">Polls</a></link>
            </ul>
            {% if user.is_authenticated %}
              <p class="navbar-text navbar-right">
                {{ user|excite|shout }}
                <a href="{% url 'accounts:logout' %}" class="navbar-link">Logout</a>
              </p>
            {% else %}
              <ul class="nav navbar-nav navbar-right">
                <li>
                  <a href="{% url 'accounts:login' %}">{{ "Login"|shout:8 }}</a></li>
                </li>
              </ul>
            {% endif %}
          </div><!--/.navbar-collapse -->
        </div>
      </div>
    {% endblock %}

    {# Some templates will want to define their own main container, they can override this block #}
    {% block main-container %}
      <div class="container main-container">
        {% block content %}{% endblock %}
      </div>
    {% endblock main-container %}

    {% block footer %}
      <div class="container">
        <hr/>
        <footer>
          <p>&copy; Company 2014</p>
        </footer>
      </div>
    {% endblock %}

    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{% static 'js/vendor/jquery-2.1.1.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.js' %}"></script>
  </body>
</html>

mysite/templates/index.html
{% extends "base.html" %}

{% block main-container %}
  <!-- Main jumbotron for a primary marketing message or call to action -->
  <div class="jumbotron">
    <div class="container">
      <h1>Hello, Cisco!</h1>
      <p>
        This is the default index template for our super-super Cisco tutorial project.
      </p>
      <p>
        We should probably figure out something better to put here. Maybe some charts showing vote counts?
      </p>
    </div>
  </div>

  <div class="container">
    <!-- Example row of columns -->
    <div class="row">
      <div class="col-md-4">
        <h2>Heading</h2>
        <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
        <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
      </div>
      <div class="col-md-4">
        <h2>Heading</h2>
        <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
        <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
      </div>
      <div class="col-md-4">
        <h2>Heading</h2>
        <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
        <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
      </div>
    </div>
  </div>
{% endblock main-container %}